name: Testing Workflow
on:
  pull_request:
    branches:
      - main
  
permissions:
  id-token: write  
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-west-2
          role-to-assume: arn:aws:iam::341877051563:role/service-role/codebuild-gh-runner-service-role
      
      - name: Run Codebuild
        uses: aws-actions/aws-codebuild-run-build@v1
        with:
          project-name: gh-runner
          artifacts-type-override: NO_ARTIFACTS
          buildspec-override: |
            version: 0.2
            phases:
               build:  
                  commands:
                    - docker run --rm --detach --publish 8080:80 --name nginx_test nginx
                    - docker ps -a
               post_build:
                  commands:
                    - echo Running StackHawk DAST Scan...
                    - docker run --rm -v ${PWD}:/hawk:rw -t -e API_KEY="hawk.Uxi702Aala1aZE4uh9Y2.hpw1hw65M0EnQKfnGCpj" -e NO_COLOUR=true stackhawk/hawkscan:latest
                    

      


